version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: my-jenkins-v3
    volumes: 
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8083:8080"
      - "5003:5000"
